# Use OpenJDK 21 as the base image
FROM eclipse-temurin:21-jre

# Install wget
RUN apt-get update && \
    apt-get install -y wget && \
    rm -rf /var/lib/apt/lists/*

# Download and install Apache Tomcat 10.1.31
RUN wget https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.31/bin/apache-tomcat-10.1.31.tar.gz && \
    tar xzf apache-tomcat-10.1.31.tar.gz && \
    mv apache-tomcat-10.1.31 /usr/local/tomcat && \
    rm apache-tomcat-10.1.31.tar.gz

# Set environment variables
ENV CATALINA_HOME /usr/local/tomcat
ENV PATH $CATALINA_HOME/bin:$PATH

# Expose ports
EXPOSE 8080

# Start Tomcat
CMD ["catalina.sh", "run"]
