package com.itextos.beacon.commonlib.dbpool;

public enum ConnectionCount
{
    INITIAL_CONNECTION_SIZE,
    MAX_IDLE_CONNECTION,
    MAX_TOTAL_CONNECTION,
    MIN_IDLE_CONNECTION,
    NUM_ACTIVE_CONNECTION,
    NUM_IDLE_CONNECTION,
    MAX_OPEN_PREPARED_STATEMENTS;
}
