export const ACCT_CONSTANTS = {
    curencyFormat: "0.0-6",
    currency: "EUR",
    genericMinFieldMinLength: 3,
    genericOptimalFieldMinLength: 3,
    genericFieldMaxLength: 40,
    passwordMinLength: 8,
    passwordMaxLength: 15,
    sms_dlt_rate: 4,
    row_rate: 4,
    wallet_rate: 8,
    intlRatewholeNumLength: 4,
    alphabets_only: "^[a-zA-Z\\s]+$",
    userNamePattern: "^[a-zA-Z0-9._-]+$",
    passwordValidation: "[*@!#%&()^~{}]",
    misspelledNewPwdMsg: "New passwords entered do not match",
    oldPasswordRequiredMsg: "Passwords cannot be changed without the old password",
    // alphabets_only_characters: "space ",[@#$%^&-_<>*+=().]
    pattern_validation: "^[a-zA-Z0-9_-\\s]+$",

    allowed_special_characters: "space , - , _ ",
    decimalNum_validation: "^-?\\d*[.,]?\\d{0,4}$",

    EMPTY_DLT_GROUPS: "You cannot proceed further as there are no DLT groups allocated",
    NO_SHARED_GROUPS: "There are no shared Groups to assign",
    NO_MATCHING_USERS: "There are no shared Users matching",
    DATE_FORMAT: "DD/MM/YYYY",
    TIME_FORMAT_12: "hh:mm A",
    TIME_FORMAT_24: "HH:mm",
    ANIMATE_TIMESET_300EASEIN: "300ms ease-in",
    ANIMATE_TIMESET_500EASEIN: "500ms ease-in",
    TIMESTAMP_FORMAT: "DD/MM/YYYY HH:mm:ss",
    // TODO: Check  where UTC property is referred
    DATE_AND_TIME_FORMAT: "DD/MM/YYYY HH:mm",

    CHARSET: ["ISO-8859-1", "ISO-8859-15", "GSM", "GSM8", "GSM7", "UTF-8", "UCS-2"],
    zeroTxMessageCOntent: "You don't have any transactions for the selected period. Please try with a different range",

    zeroTxHeadContent: "No Transactions",
    FIELD_NAMES: {
        userName: "User Name ",
        firstName: "First Name",
        lastName: "Last Name",
        company: "Company",
        contactMobile: "Mobile Number to contact",
        contactEmail: "Email Id to contact",
        walletAmount: "Wallet amount",
        SMSRate: "Rate per SMS",
        DLTRate: "Rate per DLT",
        country: "Country",
        tz: "Timezone",

    },
    BOX_MSG: {
        myAcctSharedGroups: "List of groups that was shared with you by your super user. These groups can be used during group campaign"
    },
    INFO_TXT: {
        firstName: "Alphabets of length 3 to 40 and may have space",
        lastName: "Alphabets of length 3 to 40 and may have space",
        address: "Min 3 and upto 200 characters",
        company: "Alpha numerics and may have {space, - and _ }",
        currency: "Represents the currency the account is associated with.",
        userName: "Alpha numerics of length 3 to 40 and may have {dot - _ } ",
        contactMobile: "Enter the mobile number with country code ",
        contactEmail: "Enter a valid email Id",
        walletAmount: "Supports upto max 8 digits before decimal and max 6 digits after decimal",
        SMSRate: "Amount that will be deducted per sms. Supports upto max 4 digits before decimal and max 6 digits after decimal",
        DLTRate: "DLT charges to be deducted. Supports upto max 4 digits before decimal and max 6 digits after decimal",
        //forMyaccount
        DLT_Rate: "DLT charges to be deducted.",
        SMS_Rate: "Amount that will be deducted per sms.",
        tz: "All of your dates, calendar, reports will be based on this",
        country: "This configuration will decide on the country code to use when a mobile does not have a country code",
        newLineChar: "If configured the matching characters in the message gets replaced with a newline. 1 to 3 chars max. No spaces allowed",
        allocateGroup: "You can allocate one or more template groups to this user",
        assignGroup: "Choose one from the allocated list. This will determine which DLT templates can be used when sending campaigns",
        services: "Services to be assigned to the user",
        SMPPchars: "SMPP Charset Info Text",
        walletAmountEdit: "Amount to be added/deducted. Supports upto 6 decimal place",
        myAcctWalletInfo: "Amount to be added/deducted. Supports upto 6 decimal place",
        password: "Password must have 8 characters and atleast one special Character",
    },
    ERROR_DISPLAY: {
        uniqueUserName: "Entered User Name exists already!!",
        onlyAphabets: "Only Alphabets and can have space",
        decimalPatternMsg: "Supports upto max 4 digits before decimal and max 6 digits after decimal",
        intlDecimalPatternMsg: "Supports upto max 4 digits before decimal and max 6 digits after decimal",
        rowRatedecimalPatternMsg: "Supports upto max 4 digits before decimal and max 6 digits after decimal",
        userNameAllowedChars: "Only accepts { dot - _ } ",
        fieldSplChars: "Only allowed special Characters ",
        fieldMinLength: "Minimum Length should be ",
        fieldMaxLength: "Maximum Length should be ",
        smppReqdText: "SMPP Charset is required when SMPP service is selected",
        emailPatternMsg: "Entered Email ID is not valid",
        mustHaveOneSplChar: "Password must be atleast 8 characters and should have one symbol",
        verifyPwd: "Something went wrong.",

    }

};
